# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e473e043f7622169ac1453d12974cb310ab1e6b4a09855593bb71fa5bf7079e35004ce4a7201be059e9dfa0a8731f80b1146c2adf77c3c7cccd1e79c0c3e2727

test:
  secret_key_base: 59efefd9a4696c19e325fb6b6f988a54a23e8fea7d72985d4f6a1a2517bc183df688bf2e2dc6788f0ce08160419425fdb99c054aa1ecd68c27d342f10ffa18e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
